### ISSUE TITLE
error adding new product at 'admin/product/new'

### ISSUE THREAD

**Issue by muhamadtarek** [mrvautin/expressCart#108]
Error: Missing helper: "@root.__" at handle bars hope someone guide into fixing this

**Comment by mrvautin** [comment]
I'm going to need more info. I can't replicate this error on that route.

**Comment by muhamadtarek** [comment]
excuse me a just dont get what is ' @root__' that i see through out the entire hbs templates it confuses a lot?
and another question , how is req.session accessible by hbs files ?

**Comment by mrvautin** [comment]
`@root.__` is the language translation. 

`req.session` is accessible using the render statement. You may need to look into the `express-handlebars` module for guidance.

**Comment by muhamadtarek** [comment]
yes thank you so much , but is there a diff bet '@root__' and '@root.session.cart' ? sorry if i ask too much i just want to understand every aspect of this project as i wanna build a relevant thing

**Comment by adekunlet** [comment]
Hello. Its great to be starting out my journey with expressCart, looks like an awesome project. I've just setup a new instance and logged in and having the same issue when adding/editing a product. After entering the new product details and selecting add product there is a 500 internal error so doesn't navigate to the next page. But product appears in list of products and when select it to edit it I get internal server error. I'm struggling to figure out what I have not defined while trying to add the product.

Exception has occurred: TypeError
TypeError: Cannot read property 'length' of undefined
    at Object.snip (/home/william/projects/expresscart/expressCart/app.js:319:21)
    at eval (eval at createFunctionContext (/home/william/projects/expresscart/expressCart/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:266:23), <anonymous>:12:62)
    at Object.prog [as fn] (/home/william/projects/expresscart/expressCart/node_modules/handlebars/lib/handlebars/runtime.js:205:12)
    at Object.<anonymous> (/home/william/projects/expresscart/expressCart/node_modules/handlebars/lib/handlebars/helpers/if.js:15:22)
    at Object.eval [as main] (eval at createFunctionContext (/home/william/projects/expresscart/expressCart/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:266:23), <anonymous>:52:32)
    at main (/home/william/projects/expresscart/expressCart/node_modules/handlebars/lib/handlebars/runtime.js:152:32)
    at ret (/home/william/projects/expresscart/expressCart/node_modules/handlebars/lib/handlebars/runtime.js:155:12)
    at ret (/home/william/projects/expresscart/expressCart/node_modules/handlebars/lib/handlebars/compiler/compiler.js:502:21)
    at ExpressHandlebars._renderTemplate (/home/william/projects/expresscart/expressCart/node_modules/express-handlebars/lib/express-handlebars.js:250:12)
    at ExpressHandlebars.<anonymous> (/home/william/projects/expresscart/expressCart/node_modules/express-handlebars/lib/express-handlebars.js:173:21)

**Comment by mammadjafar** [comment]
@adekunlet maybe reinstall the project, or check what did you change in code, there shouldn't be any problems there.

**Comment by mammadjafar** [comment]
> yes thank you so much , but is there a diff bet '@root__' and '@root.session.cart' ? sorry if i ask too much i just want to understand every aspect of this project as i wanna build a relevant thing

read more about handlebars, it has nothing to do with this project, you can use some other template as well..

**Comment by adekunlet** [comment]
> @adekunlet maybe reinstall the project, or check what did you change in code, there shouldn't be any problems there.

@mammadjafar thanks for the reply. I have not made any code changes. I have reinstalled the project on a droplet at Ocean Digital and deployed the code there making a clone first. The application launches fine, I am able to create the admin account and login. But again when I try to create a new product it get the same error.. Any help will be very much appreciated.

TypeError: Cannot read property 'length' of undefined
    at Object.snip (/home/mrk/expressCart/app.js:319:21)
    at eval (eval at createFunctionContext (/home/mrk/expressCart/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:266:23), <anonymous>:6:105)
    at Object.prog [as inverse] (/home/mrk/expressCart/node_modules/handlebars/dist/cjs/handlebars/runtime.js:229:12)
    at Object.<anonymous> (/home/mrk/expressCart/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:27:22)
    at eval (eval at createFunctionContext (/home/mrk/expressCart/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:266:23), <anonymous>:5:35)
    at Object.prog [as inverse] (/home/mrk/expressCart/node_modules/handlebars/dist/cjs/handlebars/runtime.js:229:12)
    at Object.<anonymous> (/home/mrk/expressCart/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:27:22)
    at Object.eval [as main] (eval at createFunctionContext (/home/mrk/expressCart/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:266:23), <anonymous>:12:32)
    at main (/home/mrk/expressCart/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:32)
    at ret (/home/mrk/expressCart/node_modules/handlebars/dist/cjs/handlebars/runtime.js:179:12)

**Comment by mrvautin** [comment]
What OS and version of Nodejs?

**Comment by adekunlet** [comment]
> What OS and version of Nodejs?

Ubuntu 18.0.4 
and 
Nodejs v8.10.0

**Comment by mrvautin** [comment]
Thanks for raising @adekunlet. I fixed in e9fcbd5a9905e5a1ed44193a618fd2edc9cc3a1c.
