### ISSUE TITLE
error is coming while running command npm start --production

### ISSUE THREAD

**Issue by abhay2701** [mrvautin/expressCart#116]
PS F:\expresscart\expressCart-master> npm start --production

> express-cart@1.1.16 start F:\expresscart\expressCart-master
> node app.js

test F:\expresscart\expressCart-master\node_modules\feather-icons\dist
F:\expresscart\expressCart-master\node_modules\connect-mongodb-session\index.js:255
    throw error;
    ^

Error: Error connecting to db: getaddrinfo ENOTFOUND mongodb mongodb:27017
    at F:\expresscart\expressCart-master\node_modules\connect-mongodb-session\index.js:75:17
    at executeCallback (F:\expresscart\expressCart-master\node_modules\mongodb\lib\operations\execute_operation.js:74:5)
    at err (F:\expresscart\expressCart-master\node_modules\mongodb\lib\operations\connect.js:209:23)
    at connectCallback (F:\expresscart\expressCart-master\node_modules\mongodb\lib\operations\connect.js:375:5)
    at topology.connect.err (F:\expresscart\expressCart-master\node_modules\mongodb\lib\operations\connect.js:608:14)
    at Object.selectServer.err [as callback] (F:\expresscart\expressCart-master\node_modules\mongodb\lib\core\sdam\topology.js:285:11)
    at Timeout.waitQueueMember.timer.setTimeout [as _onTimeout] (F:\expresscart\expressCart-master\node_modules\mongodb\lib\core\sdam\topology.js:433:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)

**Comment by mrvautin** [comment]
Looks like you can't connect to the MongoDB. Have you checked the credentials are correct?

**Comment by abhay2701** [comment]
I have solved the issue, thankyou soo much

**Comment by RiccaD** [comment]
I have a very similar problem:

Error: Error connecting to db: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at C:\Users\info\expressCart\node_modules\connect-mongodb-session\index.js:75:17
    at C:\Users\info\expressCart\node_modules\connect-mongodb-session\node_modules\mongodb\lib\utils.js:411:14
    at executeCallback (C:\Users\info\expressCart\node_modules\connect-mongodb-session\node_modules\mongodb\lib\utils.js:401:25)
    at C:\Users\info\expressCart\node_modules\connect-mongodb-session\node_modules\mongodb\lib\operations\mongo_client_ops.js:285:21
    at connectCallback (C:\Users\info\expressCart\node_modules\connect-mongodb-session\node_modules\mongodb\lib\operations\mongo_client_ops.js:265:5)
    at C:\Users\info\expressCart\node_modules\connect-mongodb-session\node_modules\mongodb\lib\operations\mongo_client_ops.js:353:14
    at Server.<anonymous> (C:\Users\info\expressCart\node_modules\connect-mongodb-session\node_modules\mongodb\lib\topologies\server.js:237:11)
    at Object.onceWrapper (events.js:422:26)
    at Server.emit (events.js:315:20)
    at Pool.<anonymous> (C:\Users\info\expressCart\node_modules\mongodb-core\lib\topologies\server.js:429:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-cart@1.1.19 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-cart@1.1.19 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\info\AppData\Roaming\npm-cache\_logs\2020-12-04T00_29_58_659Z-debug.log

Could you help me out with that?

Cheers, Ricca
