### ISSUE TITLE
Cannot read property 'productId' of undefined

### ISSUE THREAD

**Issue by OussamaBDNT** [mrvautin/expressCart#129]
Yoo Man  <3! I really like your code! 
there are some errors have found! 
When you wanna either add or subtract the quantity of a product .. you'll face an error "the error below" also if you wanna remove a product from the cart an error is showed that the Product not found in cart,  **everything it's ok till refreshing the page then only these errors will occur**.

`(node:5272) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'productId' of undefined
    at /home/bdntroot/Documents/expressCart/routes/index.js:400:94
    at Layer.handle [as handle_request] (/home/bdntroot/Documents/expressCart/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/bdntroot/Documents/expressCart/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/bdntroot/Documents/expressCart/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/bdntroot/Documents/expressCart/node_modules/express/lib/router/layer.js:95:5)
    at /home/bdntroot/Documents/expressCart/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/bdntroot/Documents/expressCart/node_modules/express/lib/router/index.js:335:12)
    at next (/home/bdntroot/Documents/expressCart/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/bdntroot/Documents/expressCart/node_modules/express/lib/router/index.js:174:3)
    at router (/home/bdntroot/Documents/expressCart/node_modules/express/lib/router/index.js:47:12)
(node:5272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

**Comment by mrvautin** [comment]
Thanks man. Unfortunately not having my code peer reviewed it causing some things to be missed.
