### ISSUE TITLE
failed to send test mail 

### ISSUE THREAD

**Issue by basharam** [mrvautin/expressCart#14]
after providing valid test email details in the settings page, test email failed to perform with below errors.

```
----------POST /admin/testEmail 200 3.835 ms - 29
{ Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials s7-v6sm10645184wrp.4 - gsmtp
    at SMTPConnection._formatError (/home/kr/ext/node-basics/expressCart/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
    at SMTPConnection._actionAUTHComplete (/home/kr/ext/node-basics/expressCart/node_modules/nodemailer/lib/smtp-connection/index.js:1335:34)
    at SMTPConnection._responseActions.push.str (/home/kr/ext/node-basics/expressCart/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
    at SMTPConnection._processResponse (/home/kr/ext/node-basics/expressCart/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
    at SMTPConnection._onData (/home/kr/ext/node-basics/expressCart/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
    at TLSSocket._socket.on.chunk (/home/kr/ext/node-basics/expressCart/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at TLSSocket.Readable.push (_stream_readable.js:136:10)
  code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials s7-v6sm10645184wrp.4 - gsmtp',
  responseCode: 535,
  command: 'AUTH PLAIN' }
```

**Comment by mrvautin** [comment]
This looks like a Gmail settings issue and not related to `expressCart`.

Maybe read the link in the error message to troubleshoot further. The readme also has a section relating to Gmail.
