### ISSUE TITLE
Second and further products added cannot add image, nor follow link once added

### ISSUE THREAD

**Issue by robrob-github** [mrvautin/expressCart#147]
Great product! This is a very useful shopping site builder.

I've set this up on Ubuntu Bionic 18.04 Linux with Node JS 13.2 and a local install on Linux of MongoDB Community Edition 4.2

Adding the first product works fine, but on adding a second or third product and then trying to edit the product following the link just goes to the first product.
Similarly once on the main site, clicking the link to the products doesn't work for me.

I see errors similar to the following:

(node:4306) UnhandledPromiseRejectionWarning: MongoError: $in needs an array
    at Connection.<anonymous> (/home/ubuntu/expressCart-master/node_modules/mongodb/lib/core/connection/pool.js:454:61)
    at Connection.emit (events.js:315:20)
    at processMessage (/home/ubuntu/expressCart-master/node_modules/mongodb/lib/core/connection/connection.js:368:10)
    at Socket.<anonymous> (/home/ubuntu/expressCart-master/node_modules/mongodb/lib/core/connection/connection.js:537:15)
    at Socket.appd_proxy (/home/ubuntu/expressCart-master/node_modules/appdynamics/lib/core/appDProxy.js:429:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
(node:4306) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
GET /product/ACMESkates - - ms - -

Is this a conflict of Node / Mongo versions? Any suggestions?

Thanks!

**Comment by mrvautin** [comment]
That is very unusual. I can't replicate the issue using the same Node and Mongodb versions. The code also only uses `$in` operators in some searches. Can you confirm you weren't searching for something? 

Can you replicate again and give details steps?

**Comment by robrob-github** [comment]
I'm going to close the issue. I think this was due to my MongoDB build with SELinux being in enforcement and my not accommodating that.
