### ISSUE TITLE
http://expresscart.mrvautin.com

### ISSUE THREAD

**Issue by antoniobrandao** [mrvautin/ExpressCart#2]
Site seems broken

    Error: Failed to lookup view "error" in views directory "/var/www/html/views"
       at Function.app.render (/var/www/html/expresscart/node_modules/express/lib/application.js:516:17)
       at ServerResponse.res.render (/var/www/html/expresscart/node_modules/express/lib/response.js:900:7)
       at /var/www/html/expresscart/app.js:237:9
       at Layer.handle_error (/var/www/html/expresscart/node_modules/express/lib/router/layer.js:58:5)
       at trim_prefix (/var/www/html/expresscart/node_modules/express/lib/router/index.js:268:13)
       at /var/www/html/expresscart/node_modules/express/lib/router/index.js:237:9
       at Function.proto.process_params (/var/www/html/expresscart/node_modules/express/lib/router/index.js:312:12)
       at /var/www/html/expresscart/node_modules/express/lib/router/index.js:228:12
       at Function.match_layer (/var/www/html/expresscart/node_modules/express/lib/router/index.js:295:3)
       at IncomingMessage.next (/var/www/html/expresscart/node_modules/express/lib/router/index.js:189:10)

**Comment by mrvautin** [comment]
Whoops. Fixed now. Thanks for letting me know @antoniobrandao.
