### ISSUE TITLE
Docker build seems broken

### ISSUE THREAD

**Issue by kmyn** [mrvautin/ExpressCart#249]
Starting the application using `docker-compose up --build` fails to start the application. 

```
Creating expresscart         ... done
Attaching to expresscart-mongodb, expresscart
expresscart    | 
expresscart    | > express-cart@1.1.19 start /var/expressCart
expresscart    | > node app.js
expresscart    | 
expresscart    | /var/expressCart/node_modules/got/dist/source/create.js:157
expresscart    |     const paginateEach = (async function* (url, options) {
expresscart    |                                         ^
expresscart    | 
expresscart    | SyntaxError: Unexpected token *
expresscart    |     at createScript (vm.js:80:10)
expresscart    |     at Object.runInThisContext (vm.js:139:10)
expresscart    |     at Module._compile (module.js:617:28)
expresscart    |     at Object.Module._extensions..js (module.js:664:10)
expresscart    |     at Module.load (module.js:566:32)
expresscart    |     at tryModuleLoad (module.js:506:12)
expresscart    |     at Function.Module._load (module.js:498:3)
expresscart    |     at Module.require (module.js:597:17)
expresscart    |     at require (internal/module.js:11:18)
expresscart    |     at Object.<anonymous> (/var/expressCart/node_modules/got/dist/source/index.js:14:18)
expresscart    | npm ERR! code ELIFECYCLE
expresscart    | npm ERR! errno 1
expresscart    | npm ERR! express-cart@1.1.19 start: `node app.js`
expresscart    | npm ERR! Exit status 1
expresscart    | npm ERR! 
expresscart    | npm ERR! Failed at the express-cart@1.1.19 start script.
expresscart    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
expresscart    | 
expresscart    | npm ERR! A complete log of this run can be found in:
expresscart    | npm ERR!     /root/.npm/_logs/2021-11-13T01_55_57_637Z-debug.log
expresscart exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by mrvautin** [comment]
I'm not a huge Docker user. Any ideas what's wrong and how to fix?

**Comment by kmyn** [comment]
> I'm not a huge Docker user. Any ideas what's wrong and how to fix?

I tried changing the node version but no luck. Suspect some issue with `got` - https://github.com/sindresorhus/got/issues/1084

**Comment by meiremans** [comment]
the current version of node in this dockerfile is a deprecated LTS.

You can change the dockerfile with mine. this one works for me.
https://github.com/meiremans/expressCart/blob/master/Dockerfile

//edit:

You said you changed the node version.
Keep in mind in this docker-compose file there is [ image: "node:8"](https://github.com/mrvautin/expressCart/blob/master/docker-compose.yml#L4) which does nothing (except naming the image node:8) because there also is a build instruction which will build the Dockerfile.

so if you changed the version in the compose file, try again with my Dockerfile.

**Comment by PraveeenPandey** [comment]
@meiremans I used your github repo of expressCart but after building when i go to localhost:1111
it doesn't have any product listed......
can you tell me the reason for this, Kindly

Thanks

**Comment by meiremans** [comment]
@PraveeenPandey You have to add the products yourself in the admin interface

**Comment by PraveeenPandey** [comment]
Thanks @meiremans,
Glad you replied, i actually tried logging and tried using admin interface.
but u cannot access the cuz lack of credentials.
i tried some which are :
Demo credentials

Admin User:
- User: `demo@test.com`
- Password: `test`

Customer:
- User: `test@test.com`
- Password: `test`

Discount code:
- 10 amount: `DEMO_AMT10`
- 10 percent: `DEMO_PCT10`

but they result in saying no account under this email.

Thanks Again
Appreciate the response.
