### ISSUE TITLE
The partial payments/paypal could not be found

### ISSUE THREAD

**Issue by craigbroadbear** [mrvautin/expressCart#48]
Hi,
I have paypal configured as my payment gateway.  When I go to check out I get an error message "The partial payments/paypal could not be found" and the following error in the log:

Error: The partial payments/paypal could not be found
    at Object.invokePartial (D:\tmp\expressCart\node_modules\handlebars\dist\cjs\handlebars\runtime.js:281:11)
    at Object.invokePartialWrapper [as invokePartial] (D:\tmp\expressCart\node_modules\handlebars\dist\cjs\handlebars\runtime.js:6
8:39)
    at eval (eval at createFunctionContext (D:\tmp\expressCart\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-com
piler.js:254:23), <anonymous>:5:31)
    at Object.prog [as fn] (D:\tmp\expressCart\node_modules\handlebars\dist\cjs\handlebars\runtime.js:221:12)
    at Object.ifCond (D:\tmp\expressCart\app.js:187:45)
    at eval (eval at createFunctionContext (D:\tmp\expressCart\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-com
piler.js:254:23), <anonymous>:5:92)
    at Object.prog [as fn] (D:\tmp\expressCart\node_modules\handlebars\dist\cjs\handlebars\runtime.js:221:12)
    at Object.<anonymous> (D:\tmp\expressCart\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:19:22)
    at Object.eval [as main] (eval at createFunctionContext (D:\tmp\expressCart\node_modules\handlebars\dist\cjs\handlebars\compil
er\javascript-compiler.js:254:23), <anonymous>:14:32)
    at main (D:\tmp\expressCart\node_modules\handlebars\dist\cjs\handlebars\runtime.js:175:32)

**Comment by mrvautin** [comment]
Check your theme. If there is an issue please submit a PR for the theme.

**Comment by craigbroadbear** [comment]
I was using default settings.  No theme changes.

**Comment by sloothes** [comment]
Works with Cloth theme but does not works with Mono theme.
