### ISSUE TITLE
node

### ISSUE THREAD

**Issue by skomuravelli** [mrvautin/expressCart#52]
F:\practice_node\expressCart\lib\common.js:685
exports.testData = async (app) => {
                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\practice_node\expressCart\app.js:13:16)

npm ER

**Comment by mrvautin** [comment]
Ancient version of Node? What Node version are you running?

**Comment by skomuravelli** [comment]
I am using node 6.11.3

**Comment by mrvautin** [comment]
Yep. Async/await was introduced in v7. Please upgrade to LTE.
