### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by VasylAndrusiak** [mrvautin/expressCart#62]
When I log in to the admin page, I see the authorization page. How to go to admin panel? Can I create my account?

**Comment by mrvautin** [comment]
You login at: `/admin/login`

**Comment by mrvautin** [comment]
Closing due to inactivity.

**Comment by Jamezslim90** [comment]
But I can't sign in with the login details I signed up with
It's logging a 404 error Not found
Please what do I need to do


Error: Not Found
    at app.use (C:\Users\HP\Desktop\expressCart-master\app.js:294:17)
    at Layer.handle [as handle_request] (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:635:15
    at next (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:47:12)
GET /admin/login_action?email=jamezslim90%http://40gmail.com&password=12345 404 29.752 ms - 6171

**Comment by mrvautin** [comment]
This not the same issue. You are getting 404 as there is no GET listener on `/admin/login_action`. What link takes you here? There is no reference to any redirects to this URL.

**Comment by Jamezslim90** [comment]
This is the sign-in link

http://localhost:1111/admin/login

when I click the submit button, I get  the error

**Comment by Jamezslim90** [comment]
I get this redirect (/admin/login_action) when I tried to sign in from the
/admin/login route.

/admin/login  is the link that takes me there

Thanks
