### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by Ajinkya-M** [mrvautin/expressCart#77]
I am getting following error while $npm install 
```
npm WARN engine eslint@6.1.0: wanted: {"node":"^8.10.0 || ^10.13.0 || >=11.10.1"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine ava@2.2.0: wanted: {"node":">=8.9.4 <9 || >=10.0.0 <11 || >=12.0.0"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine node-cron@2.0.3: wanted: {"node":">=6.0.0"} (current: {"node":"0.10.30","npm":"1.4.21"})
 
> node-cron@2.0.3 postinstall /home/asanjaymanka/projects/javascriptProjects/repoProjects/expressCart/node_modules/node-cron
> opencollective-postinstall

\
/home/asanjaymanka/projects/javascriptProjects/repoProjects/expressCart/node_modules/node-cron/node_modules/opencollective-postinstall/index.js:14
    console.log(`\u001b[96m\u001b[1mThank you for using ${pkg.name}!\u001b[96m
                ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Linux 3.10.0-693.el7.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/asanjaymanka/projects/javascriptProjects/repoProjects/expressCart
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm WARN engine fibers@4.0.1: wanted: {"node":">=10.0.0"} (current: {"node":"0.10.30","npm":"1.4.21"})
```

**Comment by mrvautin** [comment]
You are running a REALLY old version of Node: v0.10.30. Update to LTS at least.

**Comment by Ajinkya-M** [comment]
Thank you for your response. I'll update node
