### ISSUE TITLE
I Can not Sign in to Admin Dashboard after successful Sign up

### ISSUE THREAD

**Issue by Jamezslim90** [mrvautin/expressCart#84]
Hello
I downloaded the expressCart eCommerce app

After connecting to mLab, I started the app
navigated to the admin route and signed up to complete the setup
It confirmed that a user already exists

But I can't sign in with the login details I signed up with
It's logging a 404 error Not found

Please what do I need to do
Thank

**Comment by Jamezslim90** [comment]
> Hello
> I downloaded the expressCart eCommerce app
> 
> After connecting to mLab, I started the app
> navigated to the admin route and signed up to complete the setup
> It confirmed that a user already exists
> 
> But I can't sign in with the login details I signed up with
> It's logging a 404 error Not found
> 
> Please what do I need to do
> Thank

Error: Not Found
    at app.use (C:\Users\HP\Desktop\expressCart-master\app.js:294:17)
    at Layer.handle [as handle_request] (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:635:15
    at next (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\HP\Desktop\expressCart-master\node_modules\express\lib\router\index.js:47:12)
GET /admin/login_action?email=jamezslim90%http://40gmail.com&password=12345 404 29.752 ms - 6171
